### ISSUE TITLE
Unable to Install package 

### ISSUE THREAD

**Issue by nithints** [js1010/cusim#18]
python setup.py install gives me this error
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from cuda_setup import CUDA, BUILDEXT
  File "/home/d/cusim/cuda_setup.py", line 260, in <module>
    assert CUDA is not None
AssertionError. I do have

 (cuda_envi) bash-4.2$ whereis cuda
cuda: /usr/local/cuda

bash-4.2$ echo $CUDA_HOME
/usr/local/cuda/

**Comment by js1010** [comment]
can you show me the full error log? I suspect your cuda version is out of support range.

check this

Requirements
Python3.6+
gcc / g++ (>= 5.1 for c++14)
cuda >= 7.0
Tested on Ubuntu 18.04 / GCC 7.5 / CUDA 11.1 / Python 3.6
